### ISSUE TITLE
Remove Vendor Folder from Project Repo

### ISSUE THREAD

**Issue by ghost** [kabir-baidhya/organizer#2]
Since all packages could be installed via composer maybe its good idea to remove the vendor folder from git repo to make it lightweight...

If you want to enforce certain version of other 3rd party libraries then provide the `composer.lock` file and `composer install` will install the version specified in the lock file instead of latest.

**Comment by kabirbaidhya** [comment]
I've removed the `vendor` directory & updated the `.gitignore` file.
